# Application Configuration
spring.application.name=inventory-service
server.port=8080

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Metrics Configuration
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Tracing Configuration
management.tracing.sampling.probability=1.0
management.tracing.enabled=true
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces

# Logging Configuration
logging.level.com.nashtech.inventory=DEBUG
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
